version: "3.8"

services:
  database-pg:
    image: postgres:15
    container_name: postgresql-engine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ajied
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: project-dibimbing
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ajied_d@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database-pg

volumes:
  postgres-data:
  pgadmin-data: